# Generated by Django 4.2.2 on 2023-06-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tastmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
