# Generated by Django 4.2.2 on 2023-06-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tastmodel_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tastmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tastmodel',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tastmodel',
            name='task_text',
            field=models.CharField(max_length=250),
        ),
    ]
