# Generated by Django 4.2.2 on 2023-06-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tastmodel_created_at_tastmodel_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tastmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
